apiVersion: v1
kind: Pod
metadata:
  name: rsapp
  labels:
    name: rsapp
spec:
  containers:
  - name: app
    image: thanhtv1203/swarm:nodejs
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 8085
