apiVersion: v1
kind: Pod
metadata:
  name: tools
  labels:
    app: tools
spec:
  containers:
  - name: tools
    image: thanhtv1203/coretool
    resources: {}
    command: ["/bin/bash"]
    args: ["-c", "while true; do echo 'coretool running'; sleep 10;done"]