apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: deployapp
spec:
  maxReplicas: 10
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployapp
  targetCPUUtilizationPercentage: 80