apiVersion: v1
kind: Pod
metadata:
  name: static-pod
  labels:
    app: myapp
    ungdung: ungdung1
spec:
  containers:
    - name: c1
      image: thanhtv1203/swarm:nodejs
      resources:
          limits:
            memory: "100M"
            cpu: "100m"
      ports:
        - name: web
          containerPort: 8085
          protocol: TCP